<a href="https://colab.research.google.com/github/navroz-lamba/DS-Unit-2-Kaggle-Challenge/blob/master/Assignment_221.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split

# to be able to view all the columns in the head 
pd.set_option('display.max_columns', None)

train = pd.merge(pd.read_csv('https://raw.githubusercontent.com/LambdaSchool/DS-Unit-2-Kaggle-Challenge/master/data/waterpumps/train_features.csv'), 
                 pd.read_csv('https://raw.githubusercontent.com/LambdaSchool/DS-Unit-2-Kaggle-Challenge/master/data/waterpumps/train_labels.csv')).set_index('id')

test = pd.read_csv('https://raw.githubusercontent.com/LambdaSchool/DS-Unit-2-Kaggle-Challenge/master/data/waterpumps/test_features.csv', index_col='id')

sample_submission = pd.read_csv('https://raw.githubusercontent.com/LambdaSchool/DS-Unit-2-Kaggle-Challenge/master/data/waterpumps/sample_submission.csv')

train.shape, test.shape

((59400, 40), (14358, 39))

# EDA

In [ ]:
train.head(50)

,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,basin,subvillage,region,region_code,district_code,lga,ward,population,public_meeting,recorded_by,scheme_management,scheme_name,permit,construction_year,extraction_type,extraction_type_group,extraction_type_class,management,management_group,payment,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group,status_group
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
69572,6000.0,2011-03-14,Roman,1390,Roman,34.938093,-9.856322e+00,none,0,Lake Nyasa,Mnyusi B,Iringa,11,5,Ludewa,Mundindi,109,True,GeoData Consultants Ltd,VWC,Roman,False,1999,gravity,gravity,gravity,vwc,user-group,pay annually,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe,functional
8776,0.0,2013-03-06,Grumeti,1399,GRUMETI,34.698766,-2.147466e+00,Zahanati,0,Lake Victoria,Nyamara,Mara,20,2,Serengeti,Natta,280,NaN,GeoData Consultants Ltd,Other,NaN,True,2010,gravity,gravity,gravity,wug,user-group,never pay,never pay,soft,good,insufficient,insufficient,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe,functional
34310,25.0,2013-02-25,Lottery Club,686,World vision,37.460664,-3.821329e+00,Kwa Mahundi,0,Pangani,Majengo,Manyara,21,4,Simanjiro,Ngorika,250,True,GeoData Consultants Ltd,VWC,Nyumba ya mungu pipe scheme,True,2009,gravity,gravity,gravity,vwc,user-group,pay per bucket,per bucket,soft,good,enough,enough,dam,dam,surface,communal standpipe multiple,communal standpipe,functional
67743,0.0,2013-01-28,Unicef,263,UNICEF,38.486161,-1.115530e+01,Zahanati Ya Nanyumbu,0,Ruvuma / Southern Coast,Mahakamani,Mtwara,90,63,Nanyumbu,Nanyumbu,58,True,GeoData Consultants Ltd,VWC,NaN,True,1986,submersible,submersible,submersible,vwc,user-group,never pay,never pay,soft,good,dry,dry,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe,non functional
19728,0.0,2011-07-13,Action In A,0,Artisan,31.130847,-1.825359e+00,Shuleni,0,Lake Victoria,Kyanyamisa,Kagera,18,1,Karagwe,Nyakasimbi,0,True,GeoData Consultants Ltd,NaN,NaN,True,0,gravity,gravity,gravity,other,other,never pay,never pay,soft,good,seasonal,seasonal,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe,functional
9944,20.0,2011-03-13,Mkinga Distric Coun,0,DWE,39.172796,-4.765587e+00,Tajiri,0,Pangani,Moa/Mwereme,Tanga,4,8,Mkinga,Moa,1,True,GeoData Consultants Ltd,VWC,Zingibali,True,2009,submersible,submersible,submersible,vwc,user-group,pay per bucket,per bucket,salty,salty,enough,enough,other,other,unknown,communal standpipe multiple,communal standpipe,functional
19816,0.0,2012-10-01,Dwsp,0,DWSP,33.362410,-3.766365e+00,Kwa Ngomho,0,Internal,Ishinabulandi,Shinyanga,17,3,Shinyanga Rural,Samuye,0,True,GeoData Consultants Ltd,VWC,NaN,True,0,swn 80,swn 80,handpump,vwc,user-group,never pay,never pay,soft,good,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump,non functional
54551,0.0,2012-10-09,Rwssp,0,DWE,32.620617,-4.226198e+00,Tushirikiane,0,Lake Tanganyika,Nyawishi Center,Shinyanga,17,3,Kahama,Chambo,0,True,GeoData Consultants Ltd,NaN,NaN,True,0,nira/tanira,nira/tanira,handpump,wug,user-group,unknown,unknown,milky,milky,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump,non functional
53934,0.0,2012-11-03,Wateraid,0,Water Aid,32.711100,-5.146712e+00,Kwa Ramadhan Musa,0,Lake Tanganyika,Imalauduki,Tabora,14,6,Tabora Urban,Itetemia,0,True,GeoData Consultants Ltd,VWC,NaN,True,0,india mark ii,india mark ii,handpump,vwc,user-group,never pay,never pay,salty,salty,seasonal,seasonal,machine dbh,borehole,groundwater,hand pump,hand pump,non functional
46144,0.0,2011-08-03,Isingiro Ho,0,Artisan,30.626991,-1.257051e+00,Kwapeto,0,Lake Victoria,Mkonomre,Kagera,18,1,Karagwe,Kaisho,0,True,GeoData Consultants Ltd,NaN,NaN,True,0,nira/tanira,nira/tanira,handpump,vwc,user-group,never pay,never pay,soft,good,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump,functional
49056,0.0,2011-02-20,Private,62,Private,39.209518,-7.034139e+00,Mzee Hokororo,0,Wami / Ruvu,Mizugo,Pwani,60,43,Mkuranga,Tambani,345,True,GeoData Consultants Ltd,Private operator,NaN,False,2011,submersible,submersible,submersible,private operator,commercial,never pay,never pay,salty,salty,enough,enough,machine dbh,borehole,groundwater,other,other,functional
50409,200.0,2013-02-18,Danida,1062,DANIDA,35.770258,-1.057417e+01,Kwa Alid Nchimbi,0,Lake Nyasa,Ngondombwito,Ruvuma,10,5,Namtumbo,Msindo,250,True,GeoData Consultants Ltd,WUG,NaN,False,1987,swn 80,swn 80,handpump,wug,user-group,pay when scheme fails,on failure,soft,good,insufficient,insufficient,shallow well,shallow well,groundwater,hand pump,hand pump,functional
36957,0.0,2012-10-14,World Vision,0,World vision,33.798106,-3.290194e+00,Pamba,0,Internal,Nkilifa,Shinyanga,17,2,Maswa,Busilili,0,True,GeoData Consultants Ltd,WUG,NaN,False,0,nira/tanira,nira/tanira,handpump,wug,user-group,other,other,soft,good,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump,functional
50495,0.0,2013-03-15,Lawatefuka Water Supply,1368,Lawatefuka water sup,37.092574,-3.181783e+00,Kwa John Izack Mmari,0,Pangani,Omarini,Kilimanjaro,3,7,Siha,Siha Kaskazini,1,True,GeoData Consultants Ltd,Water Board,BL Bondeni,True,2009,gravity,gravity,gravity,water board,user-group,pay monthly,monthly,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe,functional
53752,0.0,2012-10-20,Biore,0,WEDECO,34.364073,-3.629333e+00,Mwabasabi,0,Internal,Mwabasabi,Shinyanga,17,6,Meatu,Nkoma,0,True,GeoData Consultants Ltd,WUG,None,True,0,nira/tanira,nira/tanira,handpump,wug,user-group,never pay,never pay,soft,good,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump,functional
61848,0.0,2011-08-04,Rudep,1645,DWE,31.444121,-8.274962e+00,Kwa Juvenal Ching'Ombe,0,Lake Tanganyika,Tunzi,Rukwa,15,2,Sumbawanga Rural,Mkowe,200,True,GeoData Consultants Ltd,VWC,NaN,False,1991,swn 80,swn 80,handpump,vwc,user-group,never pay,never pay,soft,good,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump,functional
48451,500.0,2011-07-04,Unicef,1703,DWE,34.642439,-9.106185e+00,Kwa John Mtenzi,0,Rufiji,Kidudumo,Iringa,11,4,Njombe,Mdandu,35,True,GeoData Consultants Ltd,WUA,wanging'ombe water supply s,True,1978,gravity,gravity,gravity,wua,user-group,pay monthly,monthly,soft,good,dry,dry,river,river/lake,surface,communal standpipe,communal standpipe,non functional
58155,0.0,2011-09-04,Unicef,1656,DWE,34.569266,-9.085515e+00,Kwa Rose Chaula,0,Rufiji,Yeriko,Iringa,11,4,Njombe,Usuka,50,True,GeoData Consultants Ltd,WUA,wanging'ombe water supply s,True,1978,gravity,gravity,gravity,wua,user-group,pay when scheme fails,on failure,soft,good,dry,dry,river,river/lake,surface,communal standpipe,communal standpipe,non functional
34169,0.0,2011-07-22,Hesawa,1162,DWE,32.920154,-1.947868e+00,Ngomee,0,Lake Victoria,Center,Mwanza,19,1,Ukerewe,Ilangala,1000,NaN,GeoData Consultants Ltd,NaN,NaN,True,1999,other,other,other,vwc,user-group,never pay,never pay,milky,milky,insufficient,insufficient,spring,spring,groundwater,other,other,functional needs repair
18274,500.0,2011-02-22,Danida,1763,Danid,34.508967,-9.894412e+00,none,0,Lake Nyasa,Manyanya,Iringa,11,5,Ludewa,Mawengi,1,True,GeoData Consultants Ltd,VWC,Makanj,True,1992,gravity,gravity,gravity,vwc,user-group,pay annually,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe,functional
48375,200.0,2011-02-27,Twe,2216,TWE,34.473430,-9.594990e+00,none,0,Lake Nyasa,Majengo,Iringa,11,4,Njombe,Matola,4,True,GeoData Consultants Ltd,VWC,Kidabu,False,2008,gravity,gravity,gravity,vwc,user-group,pay monthly,monthly,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe,functional
6091,0.0,2013-02-10,Dwsp,0,DWE,0.000000,-2.000000e-08,Muungano,0,Lake Victoria,Ibabachegu,Shinyanga,17,1,Bariadi,Ikungulyabashashi,0,NaN,GeoData Consultants Ltd,WUG,NaN,False,0,swn 80,swn 80,handpump,wug,user-group,unknown,unknown,unknown,unknown,unknown,unknown,shallow well,shallow well,groundwater,hand pump,hand pump,functional
58500,0.0,2011-10-04,Unicef,1510,DWE,34.586901,-8.980014e+00,Shuleni,0,Rufiji,Mkanivega,Iringa,11,4,Njombe,Usuka,350,True,GeoData Consultants Ltd,WUA,wanging'ombe water supply s,True,1978,gravity,gravity,gravity,wua,user-group,never pay,never pay,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe,functional needs repair
37862,500.0,2013-11-03,Isf,672,ISF,37.940029,-4.125595e+00,Kinonga,0,Pangani,Mkonga Juu,Kilimanjaro,3,3,Same,Kisiwani,210,True,GeoData Consultants Ltd,Water authority,Mashangwi,True,2011,gravity,gravity,gravity,vwc,user-group,pay monthly,monthly,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe,functional
51058,0.0,2013-01-21,African Development Bank,1645,DWE,29.747066,-4.495568e+00,Kamsasa,0,Lake Tanganyika,Msasa,Kigoma,16,3,Kigoma Rural,Mkigo,156,False,GeoData Consultants Ltd,VWC,Quick wins Program,True,2009,gravity,gravity,gravity,vwc,user-group,unknown,unknown,soft,good,enough,enough,spring,spring,groundwater,improved spring,improved spring,functional
22308,0.0,2013-02-25,Government Of Tanzania,1273,DWE,37.422751,-3.317536e+00,Kwa Tukai,0,Pangani,Kitereni,Kilimanjaro,3,4,Moshi Rural,Kimochi,140,True,GeoData Consultants Ltd,VWC,Komaka mandaka,True,1974,gravity,gravity,gravity,vwc,user-group,unknown,unknown,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe,functional needs repair
55012,500.0,2013-01-16,Sobodo,200,Kilolo Star,39.370777,-9.942532e+00,Ruhoma Primary School,0,Ruvuma / Southern Coast,Shuleni,Lindi,80,23,Lindi Rural,Rutamba,260,False,GeoData Consultants Ltd,VWC,Sobodo Borehole Scheme,False,2011,india mark ii,india mark ii,handpump,vwc,user-group,pay monthly,monthly,soft,good,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump,functional
20145,0.0,2011-07-11,Hesawa,0,DWE,31.104257,-1.735361e+00,Kwawilliam,0,Lake Victoria,Chakahaya,Kagera,18,1,Karagwe,Nyaishozi,0,True,GeoData Consultants Ltd,NaN,NaN,True,0,nira/tanira,nira/tanira,handpump,vwc,user-group,never pay,never pay,soft,good,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump,functional
19685,0.0,2013-03-05,Government Of Tanzania,1443,District council,37.611126,-3.263526e+00,Kwa Kibakaya,0,Pangani,Kiyao,Kilimanjaro,3,1,Rombo,Mengwe Manda,1,True,GeoData Consultants Ltd,Company,Kitukuni water supply,True,2000,gravity,gravity,gravity,company,commercial,pay monthly,monthly,soft,good,insufficient,insufficient,spring,spring,groundwater,communal standpipe,communal standpipe,non functional
69124,0.0,2013-03-16,Lawatefuka Water Supply,1256,Lawatefuka water sup,37.061688,-3.191989e+00,Kwa Willium Kinda,0,Pangani,Merali,Kilimanjaro,3,7,Siha,Siha Kati,1,True,GeoData Consultants Ltd,Water Board,BL Mwakikoti,True,2002,gravity,gravity,gravity,water board,user-group,pay monthly,monthly,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe,functional
46804,0.0,2011-03-23,Water,0,Water,36.108312,-5.791000e+00,Ngosi,0,Wami / Ruvu,Karume,Dodoma,1,4,Chamwino,Dabalo,0,True,GeoData Consultants Ltd,VWC,NaN,True,0,nira/tanira,nira/tanira,handpump,vwc,user-group,never pay,never pay,soft,good,insufficient,insufficient,shallow well,shallow well,groundwater,hand pump,hand pump,functional
6696,50.0,2011-03-16,Private Individual,180,WU,38.363555,-6.636104e+00,Kituo Cha Maziwa,0,Wami / Ruvu,Kudipera,Pwani,6,1,Bagamoyo,Chalinze,150,False,GeoData Consultants Ltd,WUA,Chalinze wate,True,2004,ksb,submersible,submersible,private operator,commercial,pay per bucket,per bucket,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe,functional
57238,0.0,2013-03-19,Government Of Tanzania,1481,DWE,37.492334,-3.290627e+00,Kwa Philip Lyimo,0,Pangani,Mosheni,Kilimanjaro,3,4,Moshi Rural,Kilema Kati,180,False,GeoData Consultants Ltd,Other,Mae pipeline,True,1972,gravity,gravity,gravity,other,other,never pay,never pay,soft,good,insufficient,insufficient,river,river/lake,surface,other,other,functional needs repair
12402,0.0,2011-03-11,Undp,1638,DWE,34.478356,-9.715910e+00,none,0,Lake Nyasa,Lupanga A,Iringa,11,5,Ludewa,Lupanga,70,True,GeoData Consultants Ltd,VWC,UNDP,False,1992,gravity,gravity,gravity,vwc,user-group,pay when scheme fails,on failure,soft,good,seasonal,seasonal,spring,spring,groundwater,communal standpipe,communal standpipe,functional
41583,0.0,2011-02-23,NaN,-41,NaN,39.812912,-7.889986e+00,Msikitini Wa Ijumaa,0,Rufiji,Kilombero B,Pwani,60,63,Mafia,Baleni,100,True,GeoData Consultants Ltd,VWC,NaN,False,0,nira/tanira,nira/tanira,handpump,vwc,user-group,never pay,never pay,salty,salty,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump,functional
57355,0.0,2013-03-28,Not Known,1546,Not known,36.618699,-3.293003e+00,Sekondari,0,Pangani,Afya,Arusha,2,2,Arusha Rural,Oltrumet,200,True,GeoData Consultants Ltd,NaN,NaN,True,2000,other,other,other,vwc,user-group,never pay,never pay,soft,good,seasonal,seasonal,rainwater harvesting,rainwater harvesting,surface,other,other,non functional
67359,0.0,2011-07-16,Danida,0,Central government,33.854345,-9.638520e+00,Office Ya Kijiji,0,Lake Nyasa,Ndanganyika,Mbeya,12,3,Kyela,Katumbasongwe,0,True,GeoData Consultants Ltd,VWC,Ngana water supplied scheme,True,0,gravity,gravity,gravity,vwc,user-group,never pay,never pay,soft,good,dry,dry,spring,spring,groundwater,communal standpipe,communal standpipe,non functional
60048,0.0,2011-03-27,Kirde,0,DWE,35.858373,-4.647906e+00,Tangi,0,Internal,Baura,Dodoma,1,1,Kondoa,Mnenia,0,True,GeoData Consultants Ltd,VWC,Itun,False,0,gravity,gravity,gravity,vwc,user-group,pay monthly,monthly,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe,functional
16583,4000.0,2011-02-20,Cefa,1955,CEFA,35.890264,-8.224399e+00,none,0,Rufiji,Mwanzala,Iringa,11,7,Kilolo,Boma la ng'ombe,100,True,GeoData Consultants Ltd,VWC,Bomala,True,2003,gravity,gravity,gravity,vwc,user-group,pay annually,annually,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe,functional
25,0.0,2013-02-11,Government Of Tanzania,1348,DWE,30.613305,-3.894561e+00,Mkuyuni,0,Lake Tanganyika,Nyabwai B,Kigoma,16,1,Kibondo,Rugongowe,230,True,GeoData Consultants Ltd,VWC,NaN,False,2002,nira/tanira,nira/tanira,handpump,vwc,user-group,unknown,unknown,soft,good,seasonal,seasonal,shallow well,shallow well,groundwater,hand pump,hand pump,non functional
70238,25.0,2013-10-03,Ces(gmbh),710,DWE,37.420027,-3.476849e+00,Kwa Lusina,0,Pangani,Reli B,Kilimanjaro,3,4,Moshi Rural,Kahe,50,True,GeoData Consultants Ltd,Water Board,Kirua kahe pumping water trust,True,2008,submersible,submersible,submersible,water board,user-group,pay per bucket,per bucket,soft,good,enough,enough,machine dbh,borehole,groundwater,communal standpipe,communal standpipe,functional
12796,500.0,2011-03-12,Government Of Tanzania,2469,Commu,33.927902,-9.204649e+00,none,0,Lake Nyasa,Kilunduwe,Iringa,11,3,Makete,Ipelele,0,True,GeoData Consultants Ltd,VWC,Misiwa,False,1986,gravity,gravity,gravity,vwc,user-group,pay when scheme fails,on failure,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe,functional
52019,500.0,2011-07-07,European Union,1803,Accra,34.814574,-9.032503e+00,Zahanati-Misssion,0,Rufiji,Sokoni,Iringa,11,4,Njombe,Mtwango,250,True,GeoData Consultants Ltd,WUG,Mtwango water supplied sche,True,2011,gravity,gravity,gravity,wug,user-group,pay monthly,monthly,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe,functional
19282,0.0,2013-01-15,NaN,1642,NaN,34.967789,-4.628921e+00,Mvae Primary,0,Internal,Mwarufyu,Singida,13,2,Singida Rural,Merya,1,True,GeoData Consultants Ltd,VWC,K,NaN,1980,mono,mono,motorpump,vwc,user-group,unknown,unknown,unknown,unknown,dry,dry,machine dbh,borehole,groundwater,communal standpipe,communal standpipe,non functional
1843,20.0,2013-03-18,Government Of Tanzania,1007,DWE,36.806079,-3.478559e+00,Kwa Bariki,0,Pangani,Marurani Juu,Arusha,2,2,Arusha Rural,Nduruma,100,True,GeoData Consultants Ltd,VWC,Machumba estate pipe line,True,2000,gravity,gravity,gravity,vwc,user-group,pay per bucket,per bucket,soft,good,insufficient,insufficient,spring,spring,groundwater,communal standpipe,communal standpipe,functional needs repair
12958,0.0,2012-10-22,World Vision,0,World Vision,33.345260,-3.838998e+00,Shimasa,0,Internal,Isenegeja,Shinyanga,17,3,Shinyanga Rural,Samuye,0,True,GeoData Consultants Ltd,WUG,SHIMASA,True,0,windmill,wind-powered,wind-powered,wug,user-group,pay when scheme fails,on failure,soft,good,enough,enough,machine dbh,borehole,groundwater,communal standpipe,communal standpipe,non functional
45111,20.0,2013-02-05,Lga,240,LGA,39.087415,-1.100060e+01,Mikoroshini,0,Ruvuma / Southern Coast,Kachulu,Mtwara,90,33,Masasi,Sindano,30,True,GeoData Consultants Ltd,VWC,NaN,True,2004,gravity,gravity,gravity,vwc,user-group,pay per bucket,per bucket,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe,functional needs repair
13620,0.0,2011-07-27,NaN,0,NaN,33.540607,-9.172905e+00,Mahakamani,0,Lake Nyasa,Mpandapanda,Mbeya,12,4,Rungwe,Kiwira,0,True,GeoData Consultants Ltd,VWC,K,NaN,0,gravity,gravity,gravity,vwc,user-group,never pay,never pay,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe,functional
18864,4000.0,2011-02-20,Cefa,1982,CEFA,35.871413,-8.227563e+00,none,0,Rufiji,Mlandege Juu,Iringa,11,7,Kilolo,Boma la ng'ombe,70,True,GeoData Consultants Ltd,VWC,Bomala,True,2003,gravity,gravity,gravity,vwc,user-group,pay annually,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe,functional
25182,1500.0,2011-04-04,District Council,2169,DWE,34.441283,-9.189878e+00,Kwa Bryson Msigwa,0,Rufiji,Ikanga,Iringa,11,4,Njombe,Wangama,20,True,GeoData Consultants Ltd,VWC,wangama water supply scheme,True,2007,gravity,gravity,gravity,vwc,user-group,pay annually,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe,functional

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 59400 entries, 69572 to 26348
Data columns (total 40 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   amount_tsh             59400 non-null  float64
 1   date_recorded          59400 non-null  object
 2   funder                 55765 non-null  object
 3   gps_height             59400 non-null  int64
 4   installer              55745 non-null  object
 5   longitude              59400 non-null  float64
 6   latitude               59400 non-null  float64
 7   wpt_name               59400 non-null  object
 8   num_private            59400 non-null  int64
 9   basin                  59400 non-null  object
 10  subvillage             59029 non-null  object
 11  region                 59400 non-null  object
 12  region_code            59400 non-null  int64
 13  district_code          59400 non-null  int64
 14  lga                    59400 non-null  object
 15  ward                   59400 non-null  object
 16  population             59400 non-null  int64
 17  public_meeting         56066 non-null  object
 18  recorded_by            59400 non-null  object
 19  scheme_management      55523 non-null  object
 20  scheme_name            31234 non-null  object
 21  permit                 56344 non-null  object
 22  construction_year      59400 non-null  int64
 23  extraction_type        59400 non-null  object
 24  extraction_type_group  59400 non-null  object
 25  extraction_type_class  59400 non-null  object
 26  management             59400 non-null  object
 27  management_group       59400 non-null  object
 28  payment                59400 non-null  object
 29  payment_type           59400 non-null  object
 30  water_quality          59400 non-null  object
 31  quality_group          59400 non-null  object
 32  quantity               59400 non-null  object
 33  quantity_group         59400 non-null  object
 34  source                 59400 non-null  object
 35  source_type            59400 non-null  object
 36  source_class           59400 non-null  object
 37  waterpoint_type        59400 non-null  object
 38  waterpoint_type_group  59400 non-null  object
 39  status_group           59400 non-null  object
dtypes: float64(3), int64(6), object(31)
memory usage: 18.6+ MB

In [ ]:
# from pandas_profiling import ProfileReport

# profile = ProfileReport(train, minimal=True).to_notebook_iframe()

In [ ]:
# filter out for Goverment of Tanzania
# train = train.loc[train['funder'] == 'Goverment of Tanzania']
# train.head()

## Working with high cardinality attributes so we don't run into problems later

In [ ]:
# Give me a col for every col that is object and if total unique values are more than 100
[col for col in train.select_dtypes(include='object').columns if train[col].nunique() > 20]

['date_recorded',
 'funder',
 'installer',
 'wpt_name',
 'subvillage',
 'region',
 'lga',
 'ward',
 'scheme_name']

In [ ]:
# this 0 needs to be converted to np.nan
mask = train['funder'] == '0'
train[mask].funder.value_counts()

0    777
Name: funder, dtype: int64

In [ ]:
# this 0 needs to be converted to np.nan
mask = train['installer'] == '0'
train[mask].installer.value_counts()

0    777
Name: installer, dtype: int64

## further continuing EDA - looking for duplicates

In [ ]:
# payment and payment_type look duplicates. lets check!
train[['payment', 'payment_type']].head(5)
# we will be dropping one of them

              payment payment_type
id
69572    pay annually     annually
8776        never pay    never pay
34310  pay per bucket   per bucket
67743       never pay    never pay
19728       never pay    never pay

In [ ]:
# water_quality and quality_group look duplicates. lets check!
train[['water_quality', 'quality_group']].head(5)
# we will be dropping one of them

      water_quality quality_group
id
69572          soft          good
8776           soft          good
34310          soft          good
67743          soft          good
19728          soft          good

In [ ]:
# lets have a look at all the geographical data together and see if we find any duplicates
train[['basin', 'subvillage', 'region', 'region_code', 'district_code', 'lga', 'ward']].tail(5)  

# Region and Region_code are telling us the same thing. 
# we will drop one of them

,basin,subvillage,region,region_code,district_code,lga,ward
id,,,,,,,
60739,Pangani,Kiduruni,Kilimanjaro,3,5,Hai,Masama Magharibi
27263,Rufiji,Igumbilo,Iringa,11,4,Njombe,Ikondo
37057,Rufiji,Madungulu,Mbeya,12,7,Mbarali,Chimala
31282,Rufiji,Mwinyi,Dodoma,1,4,Chamwino,Mvumi Makulu
26348,Wami / Ruvu,Kikatanyemba,Morogoro,5,2,Morogoro Rural,Ngerengere

In [ ]:
# lets have a look at all the extraction type attribs and see if we find any duplicates
train[['extraction_type', 'extraction_type_group', 'extraction_type_class']].tail(5)  
# we could drop 2 out of these 3 attribs

      extraction_type extraction_type_group extraction_type_class
id
60739         gravity               gravity               gravity
27263         gravity               gravity               gravity
37057          swn 80                swn 80              handpump
31282     nira/tanira           nira/tanira              handpump
26348     nira/tanira           nira/tanira              handpump

In [ ]:
# lets have a look at all the quantity group type attribs and see if we find any duplicates
train[['quantity', 'quantity_group']].tail(5)  
# we will be dropping one of them

           quantity quantity_group
id
60739        enough         enough
27263        enough         enough
37057        enough         enough
31282  insufficient   insufficient
26348        enough         enough

In [ ]:
# lets look at Management attribs
train[['management', 'management_group']].tail(5)  
# Dropping management group

        management management_group
id
60739  water board       user-group
27263          vwc       user-group
37057          vwc       user-group
31282          vwc       user-group
26348          vwc       user-group

In [ ]:
# lets look at Source attribs
train[['source', 'source_type', 'source_class']].tail(5)  
# we will we dropping two of the source or source type

             source   source_type source_class
id
60739        spring        spring  groundwater
27263         river    river/lake      surface
37057   machine dbh      borehole  groundwater
31282  shallow well  shallow well  groundwater
26348  shallow well  shallow well  groundwater

In [ ]:
# Lets look at waterpoint attribs
train[['waterpoint_type', 'waterpoint_type_group']].tail(5)  
# we will be dropping one of these

          waterpoint_type waterpoint_type_group
id
60739  communal standpipe    communal standpipe
27263  communal standpipe    communal standpipe
37057           hand pump             hand pump
31282           hand pump             hand pump
26348           hand pump             hand pump

In [ ]:
# lets make a list of cols we will be dropping so we could call it in the function 
drop_cols = ['waterpoint_type_group', 'source', 'source_class','management_group','quantity_group', 'extraction_type_group', 
                        'extraction_type_class', 'region_code', 'quality_group', 'payment_type', 'recorded_by']

## writing a function to later apply to train and test dataset

num_private and amount_tsh are highly skewed so we will keep them in mind

In [ ]:
# writing a function 
# to take care ZEROS in long and lat 
# to take care of ZEROS in funder and installer
# to take care of Cardinality 
# also, drop the repeated columns 

import numpy as np

def wrangle(X):
    
    
    # make a copy 
    X = X.copy()

    
    # replace the funky measurements with 0
    X['latitude'] = X['latitude'].replace(-2e-08, 0)
    
    
    # Replace all cols with 0s with Nan
    cols_with_zeros = ['longitude', 'latitude', 'construction_year']
    for col in cols_with_zeros:
        X[col] = X[col].replace(0, np.nan)

        
    # replace '0' in funder and installer with 'np.Nan'
    X['funder'] = X['funder'].replace('0', np.nan)
    X['installer'] = X['installer'].replace('0', np.nan)
    
    
    # fillna for construction year with bfill 
    X['construction_year'] = X['construction_year'].fillna(method = 'ffill')
    # change the dtype of date_recorded so we could extract year 
    X['date_recorded'] = pd.to_datetime(X['date_recorded'], infer_datetime_format = True)
    # Extracting year and assigning a new column
    X['year_recorded'] = X['date_recorded'].dt.year
    # making a new column, time since inspection
    X['time_since_inspection'] = X['year_recorded'] - X['construction_year']

    
    # convert district code and construction year to object 
    X['district_code'] = X['district_code'].astype('object')
    X['year_recorded'] = X['year_recorded'].astype('object')
    X['time_since_inspection'] = X['time_since_inspection'].astype('object')
 

    # fetching the high cordanility columns 
    hc_cols = [col for col in X.select_dtypes(include='object').columns 
               if X[col].nunique() > 100]
    # to iterate over every column in hc_cols
    for value in hc_cols:
    # list of top 13 
        top13 = X[value].value_counts()[:13].index
    # if not in top 13 put it under 'other'
        X.loc[~X[value].isin(top13), value] = 'Other'
    
    # lets take care of the skewed amount_tsh
    X['amount_tsh'] = np.sqrt(X['amount_tsh'])
    X['num_private'] = np.sqrt(X['num_private'])
    
    # Drop our list of repeated columns
    X = X.drop(['construction_year', 'date_recorded'] + drop_cols, axis=1)
#     X = X.drop(['date_recorded', 'year_recorded', 'contruction_year'], drop_cols, axis=1)
    
    return X

In [ ]:
# applying the function to both train and test dataset
train = wrangle(train)
test = wrangle(test)

## Split Data

In [ ]:
# Split our feature matrix and target vector
y = train['status_group']
X = train.drop('status_group', axis=1)

In [ ]:
# Train-validation split
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=10)

## Baseline

In [ ]:
print('Baseline Accuracy:', y_train.value_counts(normalize=True).max())

Baseline Accuracy: 0.5424031986531986

# Pipelines 
## making cat and num pipelines

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer

In [ ]:
# # num attribs
# num_attribs = X_train.select_dtypes(exclude='object')
# num_attribs.columns

Index(['amount_tsh', 'gps_height', 'longitude', 'latitude', 'population'], dtype='object')

In [ ]:
# # cat attributes
# cat_attribs = X_train.select_dtypes(include='object')
# cat_attribs.columns

Index(['funder', 'installer', 'wpt_name', 'basin', 'subvillage', 'region',
       'district_code', 'lga', 'ward', 'public_meeting', 'scheme_management',
       'scheme_name', 'permit', 'extraction_type', 'management', 'payment',
       'water_quality', 'quantity', 'source_type', 'waterpoint_type',
       'year_recorded', 'time_since_inspection'],
      dtype='object')

In [ ]:
# num_pipeline = Pipeline([('imputer', SimpleImputer()),
#                       ('scaler', StandardScaler())]);

# cat_pipeline = Pipeline([('imputer', SimpleImputer(strategy='most_frequent')),
#                       ('ohe', OneHotEncoder(sparse=False))]);

In [ ]:
from category_encoders import OneHotEncoder
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

from sklearn.tree import DecisionTreeClassifier

tree_model = make_pipeline(
    OneHotEncoder(use_cat_names=True),
    SimpleImputer(),
    DecisionTreeClassifier(random_state=10, min_samples_leaf=8, min_impurity_decrease=0.000078) # min_impurity_decrease=0.000081
)

tree_model.fit(X_train, y_train)

Pipeline(steps=[('onehotencoder',
                 OneHotEncoder(cols=['funder', 'installer', 'wpt_name', 'basin',
                                     'subvillage', 'region', 'district_code',
                                     'lga', 'ward', 'public_meeting',
                                     'scheme_management', 'scheme_name',
                                     'permit', 'extraction_type', 'management',
                                     'payment', 'water_quality', 'quantity',
                                     'source_type', 'waterpoint_type',
                                     'year_recorded', 'time_since_inspection'],
                               use_cat_names=True)),
                ('simpleimputer', SimpleImputer()),
                ('decisiontreeclassifier',
                 DecisionTreeClassifier(min_impurity_decrease=7.8e-05,
                                        min_samples_leaf=8, random_state=10))])

In [ ]:
print('Training Accuracy:', tree_model.score(X_train ,y_train))
print('Validation Accuracy:', tree_model.score(X_val, y_val))

Training Accuracy: 0.8128156565656566
Validation Accuracy: 0.7790404040404041

In [ ]:
y_pred = tree_model.predict(test)

In [ ]:
y_pred = pd.DataFrame(y_pred, columns=['status_group'], index=test.index)

In [ ]:
y_pred.to_csv('2020-08-10_Submission.csv')

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

tree = DecisionTreeClassifier(random_state=10)
min_samples_leaf = range(4,9)
min_impurity_decrease = range(2,11)
param_dist = dict(max_leaf_nodes = max_leaf_nodes, min_samples_leaf =min_samples_leaf ) min_samples_leaf=6, min_impurity_decrease=0.00005

rand = RandomizedSearchCV(tree, param_dist, cv=10, n_iter=10, random_state=10)
rand.fit(X_train_transformed, y_train)

RandomizedSearchCV(cv=10, estimator=DecisionTreeClassifier(random_state=10),
                   param_distributions={'max_leaf_nodes': range(3, 11),
                                        'min_samples_leaf': range(2, 11)},
                   random_state=10)

In [ ]:
print(rand.best_params_)
print(rand.best_estimator_)

{'min_samples_leaf': 8, 'max_leaf_nodes': 10}
DecisionTreeClassifier(max_leaf_nodes=10, min_samples_leaf=8, random_state=10)

In [ ]:
# # full Pipeline - combing num and cat 
# num_attribs = list(num_attribs)
# cat_attribs = list(cat_attribs)

# full_pipeline = ColumnTransformer([("cat", cat_pipeline, cat_attribs), ("num", num_pipeline, num_attribs)])

# # train set
# X_train_transformed = full_pipeline.fit_transform(X_train)
# # val set
# X_val_transformed = full_pipeline.transform(X_val)
# # # test set
# X_test_transformed = full_pipeline.transform(test)
# # X_test_transformed = full_pipeline.fit_transform(X_test)

ValueError: Found unknown categories ['HESAWA'] in column 1 during transform

In [ ]:
# from sklearn.tree import DecisionTreeClassifier

# tree_clf = DecisionTreeClassifier(random_state=10, min_impurity_decrease=0.000081)#min_impurity_decrease=0.000081
# tree_clf.fit(X_train_transformed, y_train)

# # Accuracy score for train and val set 
# print('Training Accuracy:', tree_clf.score(X_train_transformed, y_train))
# print('Validation Accuracy:', tree_clf.score(X_val_transformed, y_val))

## Regularization using RandomizedSearchCV

In [ ]:
# final_pipeline = Pipeline([('full', full_pipeline), 
#                           ('tree', DecisionTreeClassifier(random_state=10, min_impurity_decrease=0.000081))])

# final_pipeline.fit(X_train, y_train)

# y_pred = tree_clf.predict(test)

In [ ]:
train.shape

In [ ]:
test.shape

In [ ]:
test.funder.value_counts()